---
parser: '@typescript-eslint/parser'

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - standard
  - prettier

plugins:
  - prettier
  - import
  - node
  - promise
  - prefer-arrow
  - '@typescript-eslint'

parserOptions:
  ecmaVersion: 2022
  sourceType: module
  ecmaFeatures:
    globalReturn: false
    impliedStrict: true
    jsx: false

env:
  node: true
  es6: true

globals:
  NodeJS: true

rules:
  '@typescript-eslint/array-type': error
  '@typescript-eslint/ban-types': error
  '@typescript-eslint/camelcase': off
  '@typescript-eslint/consistent-type-assertions': error
  '@typescript-eslint/consistent-type-definitions': error
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/explicit-member-accessibility':
    - error
    - accessibility: explicit
  '@typescript-eslint/member-delimiter-style':
    - error
    - multiline:
        delimiter: semi
        requireLast: true
      singleline:
        delimiter: semi
        requireLast: false
  '@typescript-eslint/no-empty-function': off
  '@typescript-eslint/no-explicit-any': off # allow it in this fundamentally low-level lib
  '@typescript-eslint/no-inferrable-types': error
  '@typescript-eslint/no-namespace': error
  '@typescript-eslint/no-unused-vars': error
  '@typescript-eslint/semi':
    - error
    - always
  '@typescript-eslint/triple-slash-reference': error
  arrow-body-style: error
  camelcase: error
  comma-dangle:
    - error
    - objects: always-multiline
      arrays: always-multiline
      imports: always-multiline
      functions: never
  curly:
    - error
    - multi-line
  default-case: error
  eqeqeq:
    - error
    - smart
  guard-for-in: error
  id-blacklist:
    - error
    - any
    - Number
    - number
    - String
    - string
    - Boolean
    - boolean
    - Undefined
  #   - undefined      <-- allow it in this fundamentally low-level lib
  id-match: error
  import/no-default-export: error
  import/no-deprecated: error
  indent: error
  max-len: [2, { code: 120 }]
  new-parens: error
  no-caller: error
  no-cond-assign: error
  no-debugger: error
  no-new-wrappers: error
  no-redeclare: error
  no-return-await: error
  no-throw-literal: error
  no-underscore-dangle: error
  no-unsafe-finally: error
  no-unused-expressions: error
  no-unused-labels: error
  no-unused-vars: off
  no-useless-constructor: off
  no-var: error
  object-shorthand: error
  prefer-arrow/prefer-arrow-functions: error
  prefer-const: error
  prettier/prettier: error
  radix: error
  semi: off
  space-before-function-paren: off
  use-isnan: error
